services:
  vm-runner-api:
    # image: redteamsubnet61/rest.mdm-sn-container-runner:latest
    build:
      context: .
    restart: unless-stopped
    networks:
      - humanize-behaviour-net
    privileged: true
    user: "0:0"  # Run as root to access Docker socket
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      VM_RUNNER_API_PORT: ${VM_RUNNER_API_PORT:-8000}
    env_file:
      - path: .env
        required: false
    volumes:
      - "api-logs:${VM_RUNNER_API_LOGS_DIR:-/var/log/rest.vm-runner}"
      - "api-data:${VM_RUNNER_API_DATA_DIR:-/var/lib/rest.vm-runner}"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "${VM_RUNNER_API_PORT:-8000}:${VM_RUNNER_API_PORT:-8000}"
    tty: true


networks:
  humanize-behaviour-net:
    name: humanize-behaviour-net
    external: true

volumes:

  api-logs:
  api-data:
