services:
  vm-runner-api:
    image: redteamsubnet61/bv-bot-runner:latest
    build:
      context: .
    restart: unless-stopped
    networks:
      - bot-virus-challenge-net
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      VM_RUNNER_API_PORT: ${VM_RUNNER_API_PORT:-8000}
      DOCKER_HOST: unix:///docker-socket/docker.sock
    env_file:
      - path: .env
        required: false
    volumes:
      - "../../../volumes/storage/rest-mdm-sn-container-runner/logs:${VM_RUNNER_API_LOGS_DIR:-/var/log/rest.bv-vm-runner}"
      - "../../../volumes/storage/rest-mdm-sn-container-runner/data:${VM_RUNNER_API_DATA_DIR:-/var/lib/rest.bv-vm-runner}"
      - "dind-socket:/docker-socket"

    ports:
      - "${VM_RUNNER_API_PORT:-8000}:${VM_RUNNER_API_PORT:-8000}"

  vm-runner-dind:
    build:
      context: .
      dockerfile: Dockerfile.dind
    restart: unless-stopped
    networks:
      - bot-virus-challenge-net
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - "dind-socket:/docker-socket"
      - "dind-data:/var/lib/docker"


networks:
  bot-virus-challenge-net:
    name: bot-virus-challenge-net
    driver: bridge

volumes:
  dind-socket:
  dind-data:
