services:
  vm-runner-api:
    image: redteamsubnet61/bv-bot-runner:latest
    volumes:
      - "../../../volumes/storage/rest-mdm-sn-container-runner/logs:${VM_RUNNER_API_LOGS_DIR:-/var/log/rest.bv-vm-runner}"
      - "../../../volumes/storage/rest-mdm-sn-container-runner/data:${VM_RUNNER_API_DATA_DIR:-/var/lib/rest.bv-vm-runner}"
      - "src:/app/rest.bv-vm-runner"
    command: ["-b", "uvicorn main:app --host=0.0.0.0 --port=${MDM_PROXY_API_PORT:-8000} --no-access-log --no-server-header --proxy-headers --forwarded-allow-ips='*'"]

